
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  username: postgres
  password: postgres
  host: localhost
  database: recom_development

  
test:
  <<: *default
  username: postgres
  password: postgres
  host: localhost
  database: recom_test


production:
  <<: *default
  database: recom_production
  username: postgres
  password: postgres
